### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by hypr1x** [IvanAcoola/CS2-DMA-Cheat#2]
d3dcompiler.dll and d3dx11_43.dll not found. When I added them to the directory it still says, "cannot start problem correctly"

**Comment by IvanAcoola** [comment]
> d3dcompiler.dll and d3dx11_43.dll not found. When I added them to the directory it still says, "cannot start problem correctly"

Install direct11 dev kit

**Comment by IvanAcoola** [comment]
and clone again, added some missed libs
