### ISSUE TITLE
Unable to start normally, KEYS disappeared after prompt

### ISSUE THREAD

**Issue by lum0022** [IvanAcoola/CS2-DMA-Cheat#4]
Unable to start normally, KEYS disappeared after prompt

**Comment by lowion-cn** [comment]
Unable to start normally too. I am using kmnet. The prompt eatu:1 disappears immediately.

**Comment by IvanAcoola** [comment]
Write me in telegram with screenshots of problem

**Comment by IvanAcoola** [comment]
fixed, just improve kmbox.json (missed , )
