### ISSUE TITLE
Unable to start normally

### ISSUE THREAD

**Issue by lum0022** [IvanAcoola/CS2-DMA-Cheat#6]
[ info ] DMA Software for cs2 // https://github.com/IvanAcoola
[ Keys ] Winlogon: 6544
[ Keys ] Winver: 18363
[ Keys ] Eatu: 1
At this step, it disappears , and I don't have a kmbox

**Comment by IvanAcoola** [comment]
> [ info ] DMA Software for cs2 // https://github.com/IvanAcoola
> 
> [ Keys ] Winlogon: 6544
> 
> [ Keys ] Winver: 18363
> 
> [ Keys ] Eatu: 1
> 
> At this step, it disappears , and I don't have a kmbox

You need to have kmbox
