### ISSUE TITLE
question of kmbox

### ISSUE THREAD

**Issue by Hsupering** [IvanAcoola/CS2-DMA-Cheat#7]
Hello, I am trying to use this CS2 DMA cheating software, but I do not have a kmbox device, which prevents me from opening the cheating software. I only want to use ESP and radar functions. Can you make some modifications to the cheating software so that I can use other functions even without kmbox?

**Comment by IvanAcoola** [comment]
you can delete kmbox inizialization in code and do not use aim & trigger
